apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: albk-blog-tomcat-deploy
spec:
  replicas: 2 
  template: 
    metadata:
      labels:
        app: tomcat-cluster
    spec:
      volumes: 
      - name: albk-app
        hostPath:
          path: /usr/www/data
      containers:
      - name: tomcat-cluster
        image: tomcat:8.0.35
        resources:
          requests:
            cpu: 0.5
            memory: 200Mi
          limits:
            cpu: 1
            memory: 512Mi
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: albk-app
          mountPath: /usr/local/tomcat/webapps
