apiVersion: v1
kind: Service
metadata:
  name: k8s-demo-app-service
  labels:
    app: k8s-demo-app-service
spec:
#  type: NodePort
  selector:
    app: k8s-demo-app-deploy
  ports:
  - port: 8888
    targetPort: 80
#    nodePort: 9999
