apiVersion: v1
kind: Service
metadata:
  name: k8s-demo-mysql-service
  labels:
    app: k8s-demo-mysql-service
spec:
 # type: NodePort
  selector:
    app: k8s-demo-mysql-deploy
  ports:
  - port: 3305
    targetPort: 3306
  #  nodePort: 32706
    #protocol: TCP
